### ISSUE TITLE
Stat page Date and time in miliseconds

### ISSUE THREAD

**Issue by shraik** [librespeed/speedtest-rust#11]
On the statistics page the Date and time are in milliseconds format. Is it possible to convert them into a human-readable format?
![image](https://github.com/user-attachments/assets/96a824e3-9c6d-4648-b858-3239bf0df5a3)

**Comment by SudoDios** [comment]
Oh, okay sure

**Comment by shraik** [comment]
thank you, that's much better.
:)

**Comment by SudoDios** [comment]
Fix on [v1.3.6](https://github.com/librespeed/speedtest-rust/releases/tag/v1.3.6)
