### ISSUE TITLE
How to setup nginx/caddy before librespeed?

### ISSUE THREAD

**Issue by jonirrings** [librespeed/speedtest-rust#15]
Hello, thanks to your great work.

I've setup a caddy before speedtest-rust, but it always gets 127.0.0.1 ip. 
my caddy config is
```
http://s.o0x0o.cn, https://s.o0x0o.cn {
        root * /var/lib/librespeed-rs/assets
        file_server
        request_body {
                max_size 100MB
        }
        reverse_proxy /backend/* 127.0.0.1:18080
        tls {
                key_type p384
        }
}
```
I found `find_remote_ip_addr` always get peer_ip from connection
Is this supposed not to run behind a reverse-proxy?

**Comment by SudoDios** [comment]
Hi @jonirrings
Your welcome ☺️.
I personally work with nginx and have little experience working with caddy.
But I think your config is not complete.
In reverse_proxy you need to pass the real ip to the service (X-Real-IP).
Like this :
```
http://s.o0x0o.cn, https://s.o0x0o.cn {
    reverse_proxy /backend/* 127.0.0.1:18080 {
        header_up X-Real-IP {remote}
    }
}
```

**Comment by SudoDios** [comment]
In reverse_proxy, be aware of network restrictions and configure them.
For example, `client_max_body_size`

**Comment by jonirrings** [comment]
thanks for your quick response.
I read your great code, and found `trust_addr_proxy` is checking `X-Real-IP` header.
And setup caddy as your suggestion, but got `127.0.0.1`.

Then I run your code locally behind a nginx and a caddy.
guess what I found.

Nginx will set `X-Real-IP` as is;
Caddy will set `X-Real-IP` as `X-Real-Ip`.🤣

**Caddy canonicalizes header fields** [Link](https://caddy.community/t/header-filters-case-sensitive/18812/2)

After add serveral rows code to check `X-Real-Ip`, `librespeed-rs` return the expected address.

any solution for this situation?

**Comment by SudoDios** [comment]
How interesting and strange 😂.
Characteristic solution.  
Can you fix it in a PR ?
