### ISSUE TITLE
change server name

### ISSUE THREAD

**Issue by shraik** [librespeed/speedtest-rust#18]
It is possible to change server name ?

![image](https://github.com/user-attachments/assets/24725b26-3ef5-42b5-9e50-d6b99152d30d)

![image](https://github.com/user-attachments/assets/f6eeec28-8c1b-4342-b092-48a8205f48d2)

**Comment by SudoDios** [comment]
Hi @shraik 
Yes, it is possible

**Comment by SudoDios** [comment]
Are you sure it is assets path configured correctly?

**Comment by SudoDios** [comment]
When the assets folder is not read, this server comes up by default.
Can you show me the logs?  Or check yourself?

**Comment by shraik** [comment]
This is the log I see. Additionally, the contents of the "servers list.js" file inside the container. All configs are in the archive. I'm running Docker compose build;  docker compose up.

```
user@airflow:~/lbrspd-rust$ docker compose logs
my_speedtest  |
my_speedtest  |      _ _ _                                       _
my_speedtest  |     | (_) |__  _ __ ___  ___ _ __   ___  ___  __| |      _ __ ___
my_speedtest  |     | | | '_ \| '__/ _ \/ __| '_ \ / _ \/ _ \/ _` |_____| '__/ __|
my_speedtest  |     | | | |_) | | |  __/\__ \ |_) |  __/  __/ (_| |_____| |  \__ \
my_speedtest  |     |_|_|_.__/|_|  \___||___/ .__/ \___|\___|\__,_|     |_|  |___/
my_speedtest  |                             |_|
my_speedtest  |
my_speedtest  | [2024-12-26 12:44:41.155 INFO librespeed_rs] Config default assets directory.
my_speedtest  | [2024-12-26 12:44:41.155 INFO librespeed_rs] Configs initialized with defaults
my_speedtest  | [2024-12-26 12:44:41.155 INFO librespeed_rs] Database disabled
my_speedtest  | [2024-12-26 12:44:41.156 INFO librespeed_rs] Server started on 0.0.0.0:8080
my_speedtest  | [2024-12-26 12:44:41.156 INFO librespeed_rs] Server base url : /backend/
```

```
root@20d7974b0c8e:/usr/local/bin/assets# cat servers_list.js
function get_servers() {
    // your server list here
    return [
        {
            name : "My first server1",
            server : window.location.origin,
            dlURL: "backend/garbage", // edit this when you changed base_url in configs file
            ulURL: "backend/empty", // edit this when you changed base_url in configs file
            pingURL: "backend/empty", // edit this when you changed base_url in configs file
            getIpURL: "backend/getIP" // edit this when you changed base_url in configs file
        }
    ]
```
[lbrspd-rust.zip](https://github.com/user-attachments/files/18252812/lbrspd-rust.zip)

**Comment by SudoDios** [comment]
Server cannot load configs file : `Config default assets directory.`
I don't know how you built in Docker.

**Comment by SudoDios** [comment]
Similar to #17

**Comment by shraik** [comment]
I checked the settings, recreated the containers and everything worked as I wanted. Thank you for your patience :)
![image](https://github.com/user-attachments/assets/fe00bb0c-409b-466f-bd34-fb34e947f536)

**Comment by SudoDios** [comment]
@shraik 
You're Welcome
If there is any problem or anything, tell me so we can solve it.

**Comment by HolmanWong** [comment]
> I checked the settings, recreated the containers and everything worked as I wanted. Thank you for your patience :) ![image](https://github.com/user-attachments/assets/fe00bb0c-409b-466f-bd34-fb34e947f536)

Hello, I encountered the same problem. Can you share what did you do exactly to fix this? Thank you!
